### ISSUE TITLE
Can't mount component unless I use `export default class`

### ISSUE THREAD

**Issue by rgarner** [UseHover/preact-rails#2]
Say I have a component in

![image](https://user-images.githubusercontent.com/194511/79850266-8d3e1300-83bb-11ea-927f-b1fc8fbf24b8.png)

 (and assume I've already got JSX working with the appropriate babel plugin):

```javascript
import { h, Component } from "preact"
import React from "preact/compat";

class SubscriptionRateEstimate extends Component {
  render (props, state) {
    return (
      <h2 class='thing'>Hello, {props.hi_there}</h2>
    )
  }
}
```

I've done `yarn add preact_ujs` and added the Preact UJS boilerplate to `application.js` like so:

```javascript
var componentRequireContext = require.context("components", true);
var PreactRailsUJS = require("preact_ujs");

PreactRailsUJS.useContext(componentRequireContext)
```

And in my view I render this with:

```ruby
    <%= preact_component('SubscriptionRateEstimate', { hi_there: 'me' }) %>
```

The component shell renders with the right `data-preact-class` and `data-preact-props` attributes, but it doesn't mount. Why? Well, looking at the `getConstructor` code in Chrome, we see:

![image](https://user-images.githubusercontent.com/194511/79849902-06893600-83bb-11ea-95ff-80970047ff88.png)

... so it `require`s, but there is no `default` key in `component`.

If I add `export default` to the `class` definition in the component, it is found, but this detail isn't in the README. Should it be, or should `SubscriptionRateEstimate` be found where it is and I've missed some other detail?

**Comment by rgarner** [comment]
Ofc, Garner's law holds here, and the moment I post it I finally happen upon `export default Button` in the README, so I'll apologise profusely and thank you for an excellent gem :wink:

**Comment by simonewebdesign** [comment]
I think it would be good though to have a way of rendering non-default components...
